version: '2'
services:
    uaasampleapplication-app:
        image: uaasampleapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://uaasampleapplication-postgresql:5432/UaaSampleApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    uaasampleapplication-postgresql:
        extends:
            file: postgresql.yml
            service: uaasampleapplication-postgresql
